package main

import (
	"bufio"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	ex, err := os.Executable()
	exePath := filepath.Dir(ex)
	os.Chdir(exePath)

	fmt.Println("Create Project  (1) ")
	fmt.Println("Compile Project (2) ")
	fmt.Println("Run Project     (3) ")
	fmt.Println("")
	fmt.Println("(?) : ")
	sele := bufio.NewScanner(os.Stdin)
	sele.Scan()
	sel := sele.Text()
	if sel == "1" {
		fmt.Println("Project Name:  ")
		selet := bufio.NewScanner(os.Stdin)
		selet.Scan()
		sel1 := selet.Text()
		pname := sel1
		fmt.Println("Module Label: ")
		selet.Scan()
		sel2 := selet.Text()
		pmod := sel2

		os.Mkdir(pname, 0755)
		os.Chdir(pname)
		out, err := exec.Command("go", "mod", "init", pmod).Output()
		fmt.Println(out)
		fileName := pname + ".go"
		file, err := os.Create(fileName)
		defer file.Close()

		val := "// Generated by RpGo\npackage main\n	\n// Main Function\nfunc main() {\n	// Code here\n	\n}"
		data := []byte(val)

		erre := ioutil.WriteFile(fileName, data, 0644)

		if erre != nil || err != nil {
			log.Fatal(err)
		}

	}

	if err != nil {
		panic(err)
	}
}
