import os, os.path

def main():

    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    print("""
    
    Create Project (1)
    Compile Project (2)
    Run Project (3)
    
    
    """)
    sel=int(input("(?) : "))
    if sel == 1:
        name=input("Project Name:  ")
        label=input("Module Label: ")
        os.mkdir(name)
        os.chdir(name)
        os.system("go mod init "+label)
        f=open(name.lower()+".go", "x")
        f.write("""// Generated by RpGo
package main

// Main Function
func main() {
	// Code here

}


        """)
        f.close()

        f2=open("Compile.py", "x")
        f2.write("""import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
os.system("go build")
        """)
        f2.close()

    if sel == 2 :
        os.system("go build")
    if sel == 3 :
        file=input("Go File Name: ")
        os.system("go run "+file+".go")

main()